// Copyright (c) 2022 YA-androidapp(https://github.com/YA-androidapp) All rights reserved.

const banners = [
    {
        item_image: '104.png',
        item_title: 'ExternalMonitoring-UptimeRobot-PowerAutomate',
        item_label: 'ExternalMonitoring',
        item_summary: '簡易的な Web 監視を Power Automate で実現する',
        item_tags: ['tutorial', 'powerautomate'],
    },
    {
        item_image: '003.png',
        item_title: 'PowerApps-SakeLedger',
        item_label: 'SakeLedger',
        item_summary: 'PowerAppsでCRUDアプリを実装する手順',
        item_tags: ['tutorial', 'powerapps'],
    }
];

const ideas = [
    'CMS',
    'Eラーニング・テスト',
    'FAQ',
    'IT資産管理',
    'アンケート収集・分析',
    'イベント計画表',
    'エントリーシート受付',
    'キャッシュフロー予測',
    'キャンペーン実施管理',
    'クーポン配信',
    'クレジットカード利用履歴',
    'ゲームソフト管理',
    'サークルメンバー管理',
    'サービス価格一覧',
    'サービス提案書',
    'シフトカレンダー',
    'シラバス',
    'スキル届出',
    'スタンプカード',
    'タイムカード',
    'タスク管理',
    'チラシデザイン管理',
    'デジタルパンフレット',
    'ナレッジ管理',
    'ニュースレター配布',
    'ニュース配信',
    'ハッカソン基盤',
    'ヒヤリハット記録',
    'ファイル共有',
    'ファシリティ管理',
    'フォトアルバム',
    'フライヤー管理・印刷アプリ',
    'プレスリリース管理',
    'プレゼンテーション用タイマー',
    'プロジェクトのタイムライン',
    'プロジェクト管理',
    'プロジェクト提案',
    'ポスター管理',
    'ボランティア管理',
    'モニタリング調査',
    'ライセンス管理',
    'レストランのメニュー',
    '安全点検実施記録',
    '運転日報',
    '営業支援（SFA）',
    '営業日報',
    '家庭環境調査票',
    '開発ロードマップ',
    '外出・遅刻・早退届',
    '活動報告書',
    '患者管理',
    '寄付金管理',
    '機材貸与管理',
    '休暇申請',
    '給与明細管理',
    '許認可管理',
    '業務改善提案',
    '緊急連絡カード',
    '空室管理',
    '契約管理',
    '経費申請',
    '血糖値グラフ',
    '月間献立表',
    '月齢カレンダー',
    '建物管理',
    '検品記録',
    '研究会発表',
    '固定資産管理',
    '交通量調査',
    '広告管理',
    '広報情報管理',
    '校外学習のしおり',
    '採用管理',
    '残業届',
    '仕入れ先管理',
    '始末書',
    '支払申請管理',
    '施設入居管理',
    '資料掲示板',
    '自己紹介カード',
    '自動車運転履歴',
    '実験レポート提出',
    '社員教育管理',
    '社内申請',
    '社内報',
    '受発注管理',
    '授業計画',
    '就職管理',
    '修理受付記録',
    '住宅ローンシミュレーター',
    '住民管理',
    '出荷管理',
    '出資者名簿',
    '出席表',
    '出張届',
    '出張報告書',
    '巡回記録',
    '処方薬管理',
    '助成金管理',
    '商談記録',
    '商標管理',
    '商品カタログ',
    '小遣い追跡',
    '小切手台帳',
    '小説原稿執筆・校正',
    '消耗品購入申請',
    '証明書管理',
    '証明書発行申請',
    '賞状管理',
    '障害対応記録',
    '上申書',
    '乗務前アルコールチェック記録簿',
    '情報基盤運用',
    '新規事業企画提案',
    '新商品案内送付',
    '図面管理',
    '水質調査',
    '数独',
    '世界地図',
    '成長記録（月齢カード）',
    '生態系調査',
    '生徒管理台帳',
    '生徒指導記録簿',
    '製品レビュー',
    '製品生産量（歩留まり）集計',
    '請求書管理',
    '接待申請・承認',
    '損益計算書',
    '貸借対照表',
    '退職願',
    '退職金シミュレーター',
    '端末貸与管理',
    '誕生日リマインダー',
    '著作権管理',
    '賃貸契約管理',
    '店舗チェックイン',
    '店舗管理',
    '店舗視察報告',
    '顛末書',
    '電子カルテ',
    '電子サイン',
    '電子書籍',
    '塗り絵',
    '投薬スケジュール',
    '動画共有（ビデオ配信）',
    '道路台帳',
    '特許管理',
    '入会申込',
    '入学願書提出',
    '入居テナント管理',
    '入金消し込み',
    '年賀・中元管理',
    '配属管理',
    '売上レポート',
    '売上管理',
    '販促ノベルティ管理',
    '販売提案',
    '備品購入申請',
    '不動産管理',
    '物品購入稟議書',
    '保険契約フロー',
    '補助金管理',
    '満足度アンケート',
    '未収金管理',
    '迷子記録',
    '目標管理',
    '問診票',
    '予算管理',
    '予実管理',
    '予定表',
    '要望受付管理',
    '欲しいものリスト',
    '来客記録簿',
    '来店アンケート',
    '履歴書管理',
    '旅行プランニング',
    '旅費精算',
    '料理レシピ集',
    '臨店記録簿',
    '連絡網',
    '論文査読システム',
    '論文執筆・校正',
];

const repos = [
    {
        item_image: '2353701_s.jpg',
        item_title: 'PowerPlatform-PowerApps-AppFramework',
        item_label: 'AppFramework',
        item_summary: 'Power Appsキャンバスアプリのフレームワーク',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'list.png',
        item_title: 'PowerPlatform-PowerApps-BookManagement',
        item_label: 'BookManagement',
        item_summary: 'Power Apps キャンバスアプリで実装した蔵書管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'RoomScreen.png',
        item_title: 'PowerPlatform-PowerApps-ConferenceRoomManagement',
        item_label: 'ConferenceRoomManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した会議室予約システム',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Stamp',
        item_label: 'Stamp',
        item_summary: 'Power Apps キャンバスアプリで実装したデジタルスタンプラリーアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ReceptionCounter',
        item_label: 'ReceptionCounter',
        item_summary: 'Power Apps キャンバスアプリで実装した市役所の受付窓口順番待ちアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-FeedReader',
        item_label: 'FeedReader',
        item_summary: 'Power Apps キャンバスアプリで実装したRSSリーダー',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'Canvasapp.png',
        item_title: 'PowerPlatform-CustomConnector-CSharp-Cryptography',
        item_label: 'Cryptography',
        item_summary: 'C#カスタムコネクタで暗号化・復号化する Power Apps キャンバスアプリ',
        item_tags: ['solution', 'powerapps', 'customconnector'],
    },
    {
        item_image: 'Connector.png',
        item_title: 'PowerPlatform-CustomConnector-CSharp-XML',
        item_label: 'XML',
        item_summary: 'C#カスタムコネクタでXML文字列からJSONに変換する',
        item_tags: ['solution', 'powerapps', 'customconnector'],
    },
    {
        item_image: 'registerapp.png',
        item_title: 'PowerPlatform-PowerApps-Circulation',
        item_label: 'Circulation',
        item_summary: 'Power Apps キャンバスアプリで実装した回覧・承認アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'MapView.png',
        item_title: 'PowerPlatform-PowerApps-MapView',
        item_label: 'MapView',
        item_summary: '館内案内図・フリーアドレス座席予約などに使える、地図上に人やモノの位置を動的に描画する Power Apps キャンバスアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'app.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CustomConnector-GetPresence',
        item_label: 'Presence',
        item_summary: 'テナント内のユーザーのプレゼンスを取得する Power Apps キャンバスアプリ',
        item_tags: ['solution', 'powerapps', 'customconnector'],
    },
    {
        item_image: 'card.png',
        item_title: 'PowerPlatform-PowerApps-MapApp',
        item_label: 'MapApp',
        item_summary: 'Bing Maps を Power Apps キャンバスアプリに表示する',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Geocoding-Gsi',
        item_label: 'Geocoding',
        item_summary: '地理院地図を利用したジオコーディング（ Power Apps キャンバスアプリ）',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App.png',
        item_title: 'PowerPlatform-PowerApps-Clocks',
        item_label: 'Clocks',
        item_summary: '<a href="https://github.com/YA-androidapp/PowerPlatform-PowerApps-AppFramework">AppFramework</a>からアナログ時計コンポーネントのみ切り出し、デジタル時計を追加（ Power Apps キャンバスアプリ）',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'MainScreen.png',
        item_title: 'PowerPlatform-PowerApps-Otowa',
        item_label: 'Otowa',
        item_summary: '<a href="https://github.com/YA-androidapp/Otowa">Otowa</a> を Power Apps キャンバスアプリに移植',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'app.png',
        item_title: 'PowerPlatform-PowerApps-PasswordGen',
        item_label: 'PasswordGen',
        item_summary: 'ランダムパスワードを生成する Power Apps キャンバスアプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'PosRegister01.png',
        item_title: 'PowerPlatform-PowerApps-POS',
        item_label: 'POS',
        item_summary: 'Power Apps キャンバスアプリで実装した POS レジ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'DisplayTerminal01.png',
        item_title: 'PowerPlatform-PowerApps-WaitingList',
        item_label: 'WaitingList',
        item_summary: 'Power Apps キャンバスアプリで実装した順番待ちアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'Print01.png',
        item_title: 'PowerPlatform-PowerApps-AppointmentSystem',
        item_label: 'AppointmentSystem',
        item_summary: 'Power Apps キャンバスアプリで実装した診療予約システム',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SharePoint-HorizontalApp',
        item_label: 'SharePoint-HorizontalApp',
        item_summary: 'スキャフォールディングしたのと同等の横向き Power Apps キャンバスアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Circulation-Management-Exchange-Equipment',
        item_label: 'Equipment',
        item_summary: 'Power Apps で実装した備品管理アプリ（Exchangeリソースメールボックス使用）',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'customconnector'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MSTeams-Client',
        item_label: 'MSTeams-Client',
        item_summary: 'Power Apps キャンバスアプリで実装した Teams クライアント',
        item_tags: ['solution', 'powerapps', 'teams'],
    },
    {
        item_image: 'Teams01.png',
        item_title: 'PowerPlatform-PowerAutomate-Teams-SafetyConfirmation',
        item_label: 'SafetyConfirmation',
        item_summary: 'Power Automate でアダプティブカードを送信する安否確認システム',
        item_tags: ['solution', 'powerautomate', 'teams'],
    },
    {
        item_image: 'AP001.png',
        item_title: 'PowerPlatform-PowerAutomate-Approvals-Simple-3steps',
        item_label: 'Approvals',
        item_summary: 'Power Automate で実装した、シンプルな3段階承認ワークフロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'Flow01.png',
        item_title: 'PowerPlatform-PowerAutomate-Approvals-Dynamically',
        item_label: 'Approvals',
        item_summary: 'Power Automate で実装した、承認経路を動的に指定できるちょっと複雑な承認ワークフロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'Flow01.png',
        item_title: 'PowerPlatform-PowerAutomate-Wait',
        item_label: 'Wait',
        item_summary: 'Sleep / Wait / 指定秒数待機するクラウドフロー',
        item_tags: ['powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SocialBookmark',
        item_label: 'SocialBookmark',
        item_summary: 'Power Apps キャンバスアプリで実装したソーシャルブックマークアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'Flow01.png',
        item_title: 'PowerPlatform-PowerAutomate-SendingMailWeekly',
        item_label: 'Mail',
        item_summary: '毎週メールを送信するクラウドフロー',
        item_tags: ['powerautomate'],
    },
    {
        item_image: '104.png',
        item_title: 'ExternalMonitoring-UptimeRobot-PowerAutomate',
        item_label: 'ExternalMonitoring',
        item_summary: '簡易的な Web 監視を Power Automate で実現する',
        item_tags: ['tutorial', 'powerautomate'],
    },
    {
        item_image: '003.png',
        item_title: 'PowerApps-SakeLedger',
        item_label: 'SakeLedger',
        item_summary: 'PowerAppsでCRUDアプリを実装する手順',
        item_tags: ['tutorial', 'powerapps'],
    },
    {
        item_image: 'story.png',
        item_title: 'PowerPlatform-PowerApps-NovelGameEngine',
        item_label: 'NovelGameEngine',
        item_summary: 'Power Apps ・ Power Automate ・ Power BIを利用してゲームエンジン・ユーザーコラボレーション・分析ポータルを作成する',
        item_tags: ['powerapps', 'powerautomate', 'powerbi'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MediaPlayer',
        item_label: 'MediaPlayer',
        item_summary: 'Power Apps キャンバスアプリで実装したメディアプレーヤーアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Weather',
        item_label: 'Weather',
        item_summary: 'Power Apps キャンバスアプリで実装した天気予報アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Circulation-Management-Cars',
        item_label: 'Cars',
        item_summary: 'Power Apps で実装した社用車貸出管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Calendars',
        item_label: 'Calendars',
        item_summary: 'Power Apps キャンバスアプリで実装したカレンダー集',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'Flow01.png',
        item_title: 'PowerPlatform-PowerAutomate-CopyFlow',
        item_label: 'CopySelf',
        item_summary: 'クラウドフローを複製するクラウドフロー',
        item_tags: ['solution', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Teams-CallMemo',
        item_label: 'CallMemo',
        item_summary: 'Power Apps キャンバスアプリで入力し、 Power Automate 経由でアダプティブカードを送信する伝言メモアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-BusinessCard',
        item_label: 'BusinessCard',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した名刺申請ワークフロー・作成アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Teams-RemoteWorkReport',
        item_label: 'RemoteWorkReport',
        item_summary: 'Power Apps と Power Automate で実装したリモートワーク業務日報',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MeetingAgenda',
        item_label: 'MeetingAgenda',
        item_summary: 'Power Apps キャンバスアプリで実装した会議アジェンダテンプレート',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-FaxCover',
        item_label: 'FaxCover',
        item_summary: 'Power Apps キャンバスアプリで実装したFAX送付状印刷アプリ',
        item_tags: ['solution', 'powerapps'],
    },

    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Lipsum',
        item_label: 'Lipsum',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装したLipsum取得アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MeetingMinutes',
        item_label: 'Minutes',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した議事録アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Sticky',
        item_label: 'Sticky',
        item_summary: 'Power Apps キャンバスアプリで実装した付箋式タスク管理 (ToDo) アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Agriculture',
        item_label: 'Agriculture',
        item_summary: 'Power Apps キャンバスアプリで実装した圃場管理（スマート農業）アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PomodoroTimer',
        item_label: 'PomodoroTimer',
        item_summary: 'Power Apps キャンバスアプリで実装したポモドーロタイマーアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-EquipmentManagement',
        item_label: 'Equipments',
        item_summary: 'Power Apps で実装した備品管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SoftwareManagement',
        item_label: 'SoftwareManagement',
        item_summary: 'Power Apps と Power Automate で実装したソフトウェア管理台帳アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CustomerManagement',
        item_label: 'Customers',
        item_summary: 'Power Apps で実装した顧客管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AADUserTable',
        item_label: 'AADUser',
        item_summary: 'AAD Userテーブルのテスト（ Power Apps キャンバスアプリ）',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Members',
        item_label: 'Members',
        item_summary: 'Power Apps キャンバスアプリで実装した社員一覧アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-HealthManagement',
        item_label: 'HealthManagement',
        item_summary: 'Power Apps キャンバスアプリで実装した健康管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ShrineSearch',
        item_label: 'ShrineSearch',
        item_summary: 'Power Apps キャンバスアプリで実装した神社検索アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CSV',
        item_label: 'CSV',
        item_summary: 'Power Apps キャンバスアプリで CSV データをグリッド表示',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'Forms01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MountainClimbingRegistration',
        item_label: 'MountainClimbingRegistration',
        item_summary: 'Power Apps と Power Automate 、 Forms で実装した登山届提出システム',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'forms'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ShapeGeoJSONObjects',
        item_label: 'ShapeGeoJSONObjects',
        item_summary: 'Power Apps キャンバスアプリで GeoJSON データを表示',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Faker',
        item_label: 'Faker',
        item_summary: 'Power Apps キャンバスアプリでテストデータを生成',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-InquiryManagement',
        item_label: 'InquiryManagement',
        item_summary: 'Power Apps と Power Automate で実装した問い合わせ管理システム',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Paint',
        item_label: 'Paint',
        item_summary: 'Power Apps キャンバスアプリで実装した手書きペイント',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-VoiceActressDirectory',
        item_label: 'VoiceActressDirectory',
        item_summary: 'Power Apps で実装した声優名鑑',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'Outlook01.png',
        item_title: 'PowerPlatform-PowerAutomate-TrainingForTargetedThreat',
        item_label: 'TrainingForTargetedThreat',
        item_summary: '標的型攻撃に対する訓練を行うクラウドフロー',
        item_tags: ['solution', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-OfficeReceptionSystem',
        item_label: 'OfficeReceptionSystem',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装したオフィス向け来訪者受付アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-BusLocationSystem',
        item_label: 'BusLocationSystem',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装したバスロケシステム',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ParkingManagement',
        item_label: 'ParkingManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した駐車場管理システム',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-FoodInventoryManagement',
        item_label: 'FoodInventoryManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した冷蔵庫の中の食材を管理、賞味期限間近のものを通知するアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-VideoPlayer',
        item_label: 'VideoPlayer',
        item_summary: 'Power Apps キャンバスアプリで実装した動画プレーヤーアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ExaminationResult-RadarChart',
        item_label: 'ExaminationResult',
        item_summary: 'Power Apps キャンバスアプリで実装した試験結果通知アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PaidLeaveApplication',
        item_label: 'PaidLeaveApplication',
        item_summary: 'Power Apps で実装した有給休暇申請アプリと Power Automate で実装した承認フロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AgeChart',
        item_label: 'AgeChart',
        item_summary: 'Power Apps キャンバスアプリで実装した年齢早見表アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Teams-BranchManagement',
        item_label: 'BranchManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した支店管理・連絡アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-WBS',
        item_label: 'WBS',
        item_summary: 'Power Apps キャンバスアプリで実装したWBS',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-TransportationExpenseReport',
        item_label: 'TransportationExpenseReport',
        item_summary: 'Power Apps で実装した交通費精算申請アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-AttendanceBook',
        item_label: 'AttendanceBook',
        item_summary: 'Power Apps と Power Automate で実装した出勤簿',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CongestionForecast',
        item_label: 'CongestionForecast',
        item_summary: 'Power Apps キャンバスアプリで実装した混雑予想表アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-DocumentedEvidenceManagement',
        item_label: 'DocumentedEvidenceManagement',
        item_summary: 'Power Apps と Power Automate で実装した証憑管理アプリ（見積書・注文書・注文請書・納品書・検収書・請求書・領収書）',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ClassJournal',
        item_label: 'ClassJournal',
        item_summary: 'Power Apps で実装した学級日誌アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-TakingOutApproval',
        item_label: 'TakingOutApproval',
        item_summary: 'Power Apps と Power Automate で実装したPC持ち出し申請・承認アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Addresses',
        item_label: 'Addresses',
        item_summary: 'Power Apps で実装した住所検索アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PurchaseApproval',
        item_label: 'PurchaseApproval',
        item_summary: 'Power Apps と Power Automate で実装した物品購入申請・承認アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CongratulatoryCondolenceMoneyApplication',
        item_label: 'CongratulatoryCondolenceMoneyApplication',
        item_summary: 'Power Apps と Power Automate で実装した慶弔見舞金支給申請アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'OWA01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-OfficeTemplates',
        item_label: 'OfficeTemplates',
        item_summary: 'Power Apps と Power Automate で実装した Office ファイルへのデータ差し込み',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ProgressManagement',
        item_label: 'ProgressManagement',
        item_summary: 'Power Apps と Power Automate で実装した進捗管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-QrParticipationCertificate',
        item_label: 'QrParticipationCertificate',
        item_summary: 'Power Apps キャンバスアプリで実装した QR コードを表示する参加証アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Emoji',
        item_label: 'Emoji',
        item_summary: 'Power Apps キャンバスアプリで実装した Emoji （絵文字）を一覧表示するアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SimpleToDo',
        item_label: 'SimpleToDo',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した ToDo アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Calculator',
        item_label: 'Calculator',
        item_summary: 'Power Apps キャンバスアプリで実装した電卓アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-HierarchicalSocialBookmark',
        item_label: 'HierarchicalSocialBookmark',
        item_summary: 'Power Apps で実装した階層型ソーシャルブックマークアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-QrInventoryControl',
        item_label: 'QrInventoryControl',
        item_summary: 'Power Apps キャンバスアプリで実装した QR コードを読み取って棚卸を行う在庫管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-LostAndFoundItemsManagement',
        item_label: 'LostAndFoundItemsManagement',
        item_summary: 'Power Apps キャンバスアプリで実装した忘れ物管理アプリ（遺失物／拾得物）',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-BlogManagement',
        item_label: 'BlogManagement',
        item_summary: 'Power Apps と Power Automate で実装したブログ記事管理アプリ・承認フロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BrandManagement',
        item_label: 'BrandManagement',
        item_summary: 'Power Apps で実装したブランド資産管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ConferenceManagement',
        item_label: 'ConferenceManagement',
        item_summary: 'Power Apps で実装したカンファレンス管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-FavoriteRestaurant',
        item_label: 'FavoriteRestaurant',
        item_summary: 'Power Apps で実装したお気に入りレストラン一覧アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-RecipeBook',
        item_label: 'RecipeBook',
        item_summary: 'Power Apps で実装したレシピブックアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-TripPlanner',
        item_label: 'TripPlanner',
        item_summary: 'Power Apps で実装した旅行計画アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CallCenter',
        item_label: 'CallCenter',
        item_summary: 'Power Apps で実装したコールセンター通話履歴アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BucketList',
        item_label: 'BucketList',
        item_summary: 'Power Apps キャンバスアプリで実装した死ぬまでにやることリスト',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CarMaintenance',
        item_label: 'CarMaintenance',
        item_summary: 'Power Apps で実装した自動車整備記録簿アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-GiftShopping',
        item_label: 'GiftShopping',
        item_summary: 'Power Apps で実装したギフト購入管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-HomeInventory',
        item_label: 'HomeInventory',
        item_summary: 'Power Apps で実装したHome Inventory（自宅向け在庫管理・情報整理）アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PostMap',
        item_label: 'PostMap',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した郵便ポスト地図',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ToiletCleaningChecklist',
        item_label: 'ToiletCleaningChecklist',
        item_summary: 'Power Apps で実装したトイレ掃除チェック表アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BusinessReport',
        item_label: 'BusinessReport',
        item_summary: 'Power Apps で実装した作業報告書アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-EmergencyBagCheckList',
        item_label: 'EmergencyBagCheckList',
        item_summary: 'Power Apps で実装した非常時持出品チェックアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-InterofficeMail',
        item_label: 'InterofficeMail',
        item_summary: 'Power Apps と Power Automate で実装した社内便管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MichinoekiMap',
        item_label: 'MichinoekiMap',
        item_summary: 'Power Apps で実装した道の駅検索アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-OfficeAssets',
        item_label: 'OfficeAssets',
        item_summary: 'Power Apps と Power Automate で実装した社内資産管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ContractManagement',
        item_label: 'ContractManagement',
        item_summary: 'Power Apps と Power Automate で実装した契約書管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-StaffManagement',
        item_label: 'StaffManagement',
        item_summary: 'Power Apps と Power Automate で実装したスタッフ派遣管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-NPOManagement',
        item_label: 'NPOManagement',
        item_summary: 'Power Apps と Power Automate で実装したNPO向け管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PerformanceReview',
        item_label: 'PerformanceReview',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した査定管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SoftwareRelease',
        item_label: 'SoftwareRelease',
        item_summary: 'Power Apps と Power Automate で実装したソフトウェアリリース計画アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-LibraryInventory',
        item_label: 'LibraryInventory',
        item_summary: 'Power Apps と Power Automate で実装した図書館蔵書管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SoftwareBugTracker',
        item_label: 'SoftwareBugTracker',
        item_summary: 'Power Apps と Power Automate で実装したソフトウェアバグ追跡アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CommercialRealEstateManagement',
        item_label: 'CommercialRealEstateManagement',
        item_summary: 'Power Apps で実装した商業用物件管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MedicalInstitutionAndPharmacySearch',
        item_label: 'MedicalInstitutionAndPharmacySearch',
        item_summary: 'Power Apps と Power Automate で実装した医療機関・薬局検索アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CheckInMeeting',
        item_label: 'CheckInMeeting',
        item_summary: 'Power Apps と Power Automate で実装したチェックインミーティングアプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Nananiji',
        item_label: 'Nananiji',
        item_summary: 'Power Apps キャンバスアプリで実装したCV閲覧アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CrackInspection',
        item_label: 'CrackInspection',
        item_summary: 'Power Apps と Power Automate で実装したひび割れ点検アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-CustomerFeedback',
        item_label: 'CustomerFeedback',
        item_summary: 'Power Apps と Power Automate で実装したお客様の声管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Wordbook',
        item_label: 'Wordbook',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した単語集アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-HotelRegister',
        item_label: 'HotelRegister',
        item_summary: 'Power Apps で実装した旅館・ホテル用宿泊者名簿アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-WifiApManagement',
        item_label: 'WifiAP',
        item_summary: 'Power Apps で実装したWiFi親機管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SurveyReport',
        item_label: 'SurveyReport',
        item_summary: 'Power Apps と Power Automate で実装した調査報告書アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'Erd01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-DailyReport',
        item_label: 'DailyReport',
        item_summary: 'Power Apps と Power Automate で実装した業務日報・週報・月報アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CustomerList',
        item_label: 'CustomerList',
        item_summary: 'Power Apps で実装した顧客リスト',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MachineMaintenanceLog',
        item_label: 'MachineMaintenanceLog',
        item_summary: 'Power Apps で実装した機械整備簿',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Covid19FeverTable',
        item_label: 'Covid19FeverTable',
        item_summary: 'Power Apps と Power Automate で実装した新型コロナ対策検温表アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-StudyReport',
        item_label: 'StudyReport',
        item_summary: 'Power Apps と Power Automate で実装した研修報告アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-EventProposal',
        item_label: 'EventProposal',
        item_summary: 'Power Apps と Power Automate で実装したイベント企画書アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-InternalDecisionRequest',
        item_label: 'InternalDecisionRequest',
        item_summary: 'Power Apps と Power Automate で実装した発注向け社内稟議アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BusinessModelCanvas',
        item_label: 'BusinessModelCanvas',
        item_summary: 'Power Apps キャンバスアプリで実装した BMC （ビジネスモデルキャンバス）',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ReviewRecords',
        item_label: 'ReviewRecords',
        item_summary: 'Power Apps で実装したレビュー記録票',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SchoolTimetable',
        item_label: 'SchoolTimetable',
        item_summary: 'Power Apps で実装した授業時間割アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SkillSheet',
        item_label: 'SkillSheet',
        item_summary: 'Power Apps で実装した職務経歴書アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-OnlinePetition',
        item_label: 'OnlinePetition',
        item_summary: 'Power Apps と Power Automate で実装したオンライン署名アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'powerpages'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-QrReader',
        item_label: 'QrReader',
        item_summary: 'Power Apps キャンバスアプリで実装した QR コードリーダー',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-QrGen',
        item_label: 'QrGen',
        item_summary: 'Power Apps キャンバスアプリで実装した QR コード生成アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BusinessCompletionReport',
        item_label: 'BusinessCompletionReport',
        item_summary: 'Power Apps で実装した作業完了報告書（作業時間報告書）アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BarcodeReaderPreview22101',
        item_label: 'BarcodeReaderPreview22101',
        item_summary: 'Power Apps キャンバスアプリで実装したバーコードリーダーアプリ（Released version 22101）',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Pastebin',
        item_label: 'Pastebin',
        item_summary: 'Power Apps で実装した Pastebin',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-Dataverse-View-Filtering-Date',
        item_label: 'DataverseViewFilteringDate',
        item_summary: 'Dataverse ビューでの日時フィルタリング',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-DateTimeCalendarPicker',
        item_label: 'DateTimeCalendarPicker',
        item_summary: 'Power Apps キャンバスアプリで実装した日時選択UI',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CanvasApp-Functions-Details',
        item_label: 'CanvasAppFunctionsDetails',
        item_summary: 'Power Apps キャンバスアプリの関数の実行例',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-HamLogBook',
        item_label: 'HamLogBook',
        item_summary: 'Power Apps キャンバスアプリとモデル駆動型アプリで実装したアマチュア無線業務日誌',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-DigitalphotoFrame',
        item_label: 'DigitalphotoFrame',
        item_summary: 'Power Apps キャンバスアプリで実装したデジタルフォトフレーム',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-DrinkCounter',
        item_label: 'DrinkCounter',
        item_summary: 'Power Apps キャンバスアプリで実装したドリンクカウンター',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-GuestMembers',
        item_label: 'GuestMembers',
        item_summary: 'Power Apps キャンバスアプリで実装したゲストユーザー一覧アプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-LocalFileTransfer',
        item_label: 'LocalFileTransfer',
        item_summary: 'Power Apps キャンバスアプリで実装したローカルファイル共有アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-EventEntranceRearrangingTicket',
        item_label: 'EventEntranceRearrangingTicket',
        item_summary: 'Power Apps キャンバスアプリで実装したイベントに抽選入場を導入するための整理券アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SeatLotteryForNonTerritorialOffice',
        item_label: 'SeatLotteryForNonTerritorialOffice',
        item_summary: 'フリーアドレス制オフィスでの座席抽選を行う Power Apps キャンバスアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-BarcodeReaderVariousControls',
        item_label: 'BarcodeReaderVariousControls',
        item_summary: 'Power Apps キャンバスアプリで実装したバーコードリーダーアプリ（バーコード系コントロールの比較）',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PowerBI-AttendanceManagement',
        item_label: 'AttendanceManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した勤怠管理システム（打刻アプリ）',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'teams'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ContentsCatalogManagement',
        item_label: 'ContentsCatalogManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate 、 Power Pages で実装したコンテンツカタログページ・管理アプリ・承認フロー',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'powerpages'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-TwitterSearchByDate',
        item_label: 'TwitterSearchByDate',
        item_summary: 'Power Apps キャンバスアプリで実装したツイート (Twitter) 検索アプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AIBuilder-Lobe-AppearanceInspection',
        item_label: 'AppearanceInspection',
        item_summary: 'Lobe.ai で生成した画像認識モデルを利用する、 Power Apps キャンバスアプリで実装した外観検査アプリ',
        item_tags: ['aibuilder', 'solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AIBuilder-OCR-JPG-PNG-BMP-PDF',
        item_label: 'AIBuilderOCR',
        item_summary: 'AIBuilder のテキスト認識の事前構築済みモデルを利用する、 Power Apps キャンバスアプリで実装した OCR アプリ',
        item_tags: ['aibuilder', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AIBuilder-OCR-BusinessCard',
        item_label: 'AIBuilderBusinessCardOCR',
        item_summary: 'AIBuilder の名刺リーダーの事前構築済みモデルを利用する、 Power Apps キャンバスアプリで実装した OCR アプリ',
        item_tags: ['aibuilder', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AIBuilder-SentimentAnalysis',
        item_label: 'AIBuilderSentimentAnalysis',
        item_summary: 'AIBuilder の感情分析の事前構築済みモデルを利用する、 Power Apps キャンバスアプリで実装したテキスト感情（ネガポジ）分析アプリ',
        item_tags: ['aibuilder', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MultipleImageUploader',
        item_label: 'MultipleImageUploader',
        item_summary: 'Power Apps キャンバスアプリで実装した複数ファイル対応の画像アップローダー',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SVGAnalogClock',
        item_label: 'SVGAnalogClock',
        item_summary: 'Power Apps キャンバスアプリで実装したアナログ時計',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SuggestionBox',
        item_label: 'SuggestionBox',
        item_summary: 'Power Apps キャンバスアプリとモデル駆動型アプリで実装したデジタル目安箱',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ClaimManagement',
        item_label: 'ClaimManagement',
        item_summary: 'Power Apps モデル駆動型アプリで実装したクレーム管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-IncidentManagement',
        item_label: 'ClaimManagement',
        item_summary: 'Power Apps モデル駆動型アプリの「編集可能なグリッド」で実装したインシデント管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-CustomerVisitManagement',
        item_label: 'CustomerVisitManagement',
        item_summary: 'Power Apps モデル駆動型アプリで実装した顧客訪問管理アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-TrafficAccidentReport',
        item_label: 'TrafficAccidentReport',
        item_summary: 'Power Apps キャンバスアプリとモデル駆動型アプリで実装した交通事故報告アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-HolidayWorkReport',
        item_label: 'HolidayWorkReport',
        item_summary: 'Power Apps と Power Automate で実装した休日出勤届アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-NewYearsGreetingCard',
        item_label: 'NewYearsGreetingCard',
        item_summary: 'Power Apps と Power Automate で実装した年賀状送付管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-QAManagement',
        item_label: 'Q&AManagement',
        item_summary: 'Power Apps と Power Automate で実装したQ&A管理システム',
        item_tags: ['solution', 'powerapps', 'powerautomate', 'forms'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-AlumniManagement',
        item_label: 'AlumniManagement',
        item_summary: 'Power Apps で実装した同窓生（卒業生）管理システム',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-IdeaSharingAndVoting',
        item_label: 'IdeaManagement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装したアイディア共有・投票アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-OrganizationChart',
        item_label: 'OrganizationChart',
        item_summary: 'Power Apps キャンバスアプリで実装した Azure AD 組織図アプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-WorldClock',
        item_label: 'WorldClock',
        item_summary: 'Power Apps キャンバスアプリで実装した世界時計',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Diary',
        item_label: 'Diary',
        item_summary: 'Power Apps で実装した日記',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-IllustratedDiary',
        item_label: 'IllustratedDiary',
        item_summary: 'Power Apps キャンバスアプリで実装した絵日記',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-FuelEfficiency',
        item_label: 'FuelEfficiency',
        item_summary: 'Power Apps キャンバスアプリで実装した燃費記録アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ReadingHistory',
        item_label: 'ReadingHistory',
        item_summary: 'Power Apps キャンバスアプリで実装した読書記録アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-DomesticAccountsBook',
        item_label: 'DomesticAccountsBook',
        item_summary: 'Power Apps で実装した家計簿アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-MeetingSchedule',
        item_label: 'MeetingSchedule',
        item_summary: 'Power Apps キャンバスアプリで実装した会議予定アプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-Workout',
        item_label: 'Workout',
        item_summary: 'Power Apps キャンバスアプリで実装したワークアウト記録アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-KitchenTimer',
        item_label: 'KitchenTimer',
        item_summary: 'Power Apps キャンバスアプリで実装したキッチンタイマーアプリ',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-EquipmentManagement',
        item_label: 'EquipmentManagement',
        item_summary: 'Power Apps と Power Automate で実装した機器台帳アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-SoundVoiceRecorder',
        item_label: 'SoundVoiceRecorder',
        item_summary: 'Power Apps キャンバスアプリで実装したボイスレコーダー（録音）アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ToDoHierarchically',
        item_label: 'ToDoHierarchically',
        item_summary: 'Power Apps キャンバスアプリで実装した階層型ToDoリストアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ToDoWorkProgress',
        item_label: 'ToDoWorkProgress',
        item_summary: 'Power Apps キャンバスアプリで実装した進捗トラッカーつきToDoリストアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ToDoSortOrder',
        item_label: 'ToDoSortOrder',
        item_summary: 'Power Apps キャンバスアプリで実装した順番入れ替え機能つきToDoリストアプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'Form01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-SeminarEvaluationSurvey',
        item_label: 'SeminarEvaluationSurvey',
        item_summary: 'Power Apps と Power Automate で実装したセミナーアンケート（フィードバック）集計',
        item_tags: ['solution', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-StampingManagement',
        item_label: 'StampingManagement',
        item_summary: 'Power Apps と Power Automate で実装した捺印管理アプリ（押印記録簿／押印申請ワークフロー）',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-DocumentCirculationSystem',
        item_label: 'DocumentCirculationSystem',
        item_summary: 'Power Apps キャンバスアプリ・モデル駆動型アプリと Power Automate で実装した資料回覧システム',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-FlexibleWidthHorizontalGallery',
        item_label: 'FlexibleWidthHorizontalGallery',
        item_summary: 'Power Apps キャンバスアプリで実装した幅可変の水平ギャラリー',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ExperimentNote',
        item_label: 'ExperimentNote',
        item_summary: 'Power Apps モデル駆動型アプリと Power Automate で実装した実験ノート保全アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-PaperSubmission',
        item_label: 'PaperSubmission',
        item_summary: 'Power Apps キャンバスアプリ・モデル駆動型アプリと Power Automate で実装した学会発表論文投稿アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ConferenceRoomReservationTable',
        item_label: 'ConferenceRoomReservationTable',
        item_summary: 'Power Apps キャンバスアプリで実装した会議室予約確認表',
        item_tags: ['powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-ShareholderRegistry',
        item_label: 'ShareholderRegistry',
        item_summary: 'Power Apps キャンバスアプリで実装した株主名簿アプリ',
        item_tags: ['solution', 'powerapps'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-FacilitiesUseApplication',
        item_label: 'FacilitiesUseApplication',
        item_summary: 'Power Apps モデル駆動型アプリで実装した公共施設利用申請システム（市民ホール／公民館／スポーツ施設）・電子サイン',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-EntertainmentExpensesManagement',
        item_label: 'EntertainmentExpensesManagement',
        item_summary: 'Power Apps モデル駆動型アプリと Power Automate で実装した交際費申請・管理アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MultipurposeApprovals-CanvasApp',
        item_label: 'Approvals',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した、多目的承認ワークフロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-MultipurposeApprovals-ModelDrivenApp',
        item_label: 'Approvals',
        item_summary: 'Power Apps モデル駆動型アプリと Power Automate で実装した、多目的承認ワークフロー',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
    {
        item_image: 'App01.png',
        item_title: 'PowerPlatform-PowerApps-PowerAutomate-ScheduleArrangement',
        item_label: 'ScheduleArrangement',
        item_summary: 'Power Apps キャンバスアプリと Power Automate で実装した日程調整アプリ',
        item_tags: ['solution', 'powerapps', 'powerautomate'],
    },
];
